Venue Reaction Toggle
nightlight-app/nightlight-backend pull request #34
Opened 2023-04-17 22:48 UTC by jacoblurie29

2023-04-18 04:04 UTC, ethanratnofsky requested changes

2023-04-18 04:04 UTC, ethanratnofsky commented on src/queue/setup/workers.setup.ts
> +  console.log(`Worker # ${job.id} added. Job type: ${job.data.type}.`);
Add "[Queue]" prefix

2023-04-18 04:04 UTC, ethanratnofsky commented on src/queue/workers.ts
> +    console.log('EXPIRING REACTION: ' + userId + ' ' + venueId + ' ' + emoji);
Add "[Queue]" prefix

2023-04-18 04:04 UTC, ethanratnofsky commented on src/routes/venues.router.ts
> +venuesRouter.patch('/:venueId/reaction', toggleReactionToVenue);
```suggestion
venuesRouter.patch('/:venueId/react', toggleReactionToVenue);
```

2023-04-18 07:08 UTC, zineanteoh commented
I have also not seen lord of the rings

2023-04-19 03:54 UTC, ethanratnofsky approved these changes

2023-04-19 03:55 UTC, merged